### PR TITLE
Update support lib version to 25.2.0

### PR DESCRIPTION
**Pull request by dryaz**

### CODE REVIEW

**Comment by Malinskiy** [comment]
Hey @dilix. Thanks for the PR. Can you please fix the build?

**Comment by dryaz** [comment]
Looks like the problem happen because I've changed compile/target sdk to N (25) in this case enviroment should use java8, I'll bring 23 back, it shuold help, but also in future you could enable targeting to N by allowing Travis CI to use java8 (https://blog.travis-ci.com/2013-11-26-test-your-java-libraries-on-java-8/)

**Comment by dryaz** [comment]
I don't think it will work until CI won't use java8 to build the lib.
Using support v25 assumes that build tools and all other things also will be v25 and this assumes java8.

**Comment by dryaz** [comment]
All checks passed.

**Comment by dryaz** [comment]
@Malinskiy Hi, don't you want to merge this PR?

**Pull request closed without merging**
